python Run/Runner.py \
    --seed 42 \
    --rm_ch_list 16 17 \
    --class_weight 1 1 \
    --fold_k 5 \
    --batch_size 16 \
    --max_epochs 100 \
    --data_config data/dataConfigStimGRL.json \
    --gpu 1 \
    --model_explain "20240927 GRL + target classifier + domain classifier. 100 epoch. class_weight = {0 : 1, 1: 1}" \
    --model_name "EEGNetDomainAdaptation" \
    --monitor_value_name "val_target_loss" \
    --subject_usage "all"